### PR TITLE
Add polyfill for dual-position color stop syntax

### PR DESCRIPTION
**Pull request by fmalita**
Currently, the polyfill provides both conic-gradient rasterization and extended color stop syntax support (CSS Images Module Level 4).

But browsers may choose to ship these features discretely.  To avoid breaking existing content when e.g. conic-gradient is supported but dual-position color stops are not, we can add a standalone polyfill for the latter.

### CODE REVIEW

**Comment by LeaVerou** [comment]
Hi Florin,

Thanks for this fix!
It would be good to split the code into two polyfills: One for conic-gradient and one for the dual stop syntax, that are independent. That way, people can use the same polyfill to use dual position color stops in other types of gradients as well, regardless of conic-gradient() status.

**Comment by fmalita** [comment]
Agreed, that would be a nice/clean separation.

But for the purpose of preserving existing content, I'm not sure it would help: a separate polyfill would require content changes, right?  Unless there's a way to automatically pull this new poly from conic-gradient.js?

Also, my JS chops are super-lame, and I'm not sure I fully understand the dependencies: it seems that the two polys are coupled because they munge the same property -- so at the very least we must ensure they execute in the right order (first substitute the color stops, then the gradient).  Is there a way to "chain" distinct/external polyfills and ensure they execute in a deterministic sequence?

**Comment by LeaVerou** [comment]
By separate I meant separate in the code, not separate files. That could happen much later, and would be trivial once the code is separated.
I just meant, since you've written the code to transform existing gradient syntax, you may as well ensure it works for other types of gradients too!
That might just be a matter of changing the test to linear-gradient().

**Comment by fmalita** [comment]
Ah, I see.

Updated to test for linear-gradient() and install the dual-position poly for all gradient types.

**Comment by LeaVerou** [comment]
Merged!

**Pull request merged**
